name: Deploy to LWS

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 23 31 8 *"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement cible"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

jobs:
  deploy-test:
    if: github.event_name == 'push' || inputs.environment == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy → test.gpcoaching.fr
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /test.gpcoaching.fr/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.md
            **/.vscode/**

  deploy-prod:
    if: github.event_name == 'schedule' || inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy → gpcoaching.fr
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /gpcoaching.fr/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.md
            **/.vscode/**
